export { injectRouterMock, createProvide } from './injections'
export { createRouterMock, EmptyView } from './router'
export type { RouterMock, RouterMockOptions } from './router'
export { plugin as VueRouterMock, getRouter } from './plugin'
export type { RouterMockSpy, RouterMockSpyOptions } from './autoSpy'
