name: test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
    # We don't need to test tags
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test

      - uses: codecov/codecov-action@v5
